In [3]:
from pandas import *
from numpy import *
from os import *
from scipy.stats import kurtosis

In [4]:
chdir(r'C:\Users\DELL\Desktop\New folder\DataSets')

In [5]:
data = read_csv('boston_data.csv')

In [4]:
data

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.15876,0.0,10.81,0.0,0.413,5.961,17.5,5.2873,4.0,305.0,19.2,376.94,9.88,21.7
1,0.10328,25.0,5.13,0.0,0.453,5.927,47.2,6.9320,8.0,284.0,19.7,396.90,9.22,19.6
2,0.34940,0.0,9.90,0.0,0.544,5.972,76.7,3.1025,4.0,304.0,18.4,396.24,9.97,20.3
3,2.73397,0.0,19.58,0.0,0.871,5.597,94.9,1.5257,5.0,403.0,14.7,351.85,21.45,15.4
4,0.04337,21.0,5.64,0.0,0.439,6.115,63.0,6.8147,4.0,243.0,16.8,393.97,9.43,20.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399,9.32909,0.0,18.10,0.0,0.713,6.185,98.7,2.2616,24.0,666.0,20.2,396.90,18.13,14.1
400,51.13580,0.0,18.10,0.0,0.597,5.757,100.0,1.4130,24.0,666.0,20.2,2.60,10.11,15.0
401,0.01501,90.0,1.21,1.0,0.401,7.923,24.8,5.8850,1.0,198.0,13.6,395.52,3.16,50.0
402,0.02055,85.0,0.74,0.0,0.410,6.383,35.7,9.1876,2.0,313.0,17.3,396.90,5.77,24.7
403,0.08244,30.0,4.93,0.0,0.428,6.481,18.5,6.1899,6.0,300.0,16.6,379.41,6.36,23.7

In [92]:
data.dtypes

crim       float64
zn         float64
indus      float64
chas       float64
nox        float64
rm         float64
age        float64
dis        float64
rad        float64
tax        float64
ptratio    float64
black      float64
lstat      float64
medv       float64
dtype: object

In [93]:
data.describe()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
count,404.000000,404.000000,404.000000,404.000000,404.000000,404.00000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000
mean,3.730912,10.509901,11.189901,0.069307,0.556710,6.30145,68.601733,3.799666,9.836634,411.688119,18.444554,355.068243,12.598936,22.312376
std,8.943922,22.053733,6.814909,0.254290,0.117321,0.67583,28.066143,2.109916,8.834741,171.073553,2.150295,94.489572,6.925173,8.837019
min,0.006320,0.000000,0.460000,0.000000,0.392000,3.56100,2.900000,1.169100,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082382,0.000000,5.190000,0.000000,0.453000,5.90275,45.800000,2.087875,4.000000,281.000000,17.375000,374.710000,7.135000,17.100000
50%,0.253715,0.000000,9.795000,0.000000,0.538000,6.23050,76.600000,3.207450,5.000000,330.000000,19.000000,391.065000,11.265000,21.400000
75%,4.053158,12.500000,18.100000,0.000000,0.631000,6.62925,94.150000,5.222125,24.000000,666.000000,20.200000,396.007500,16.910000,25.000000
max,88.976200,95.000000,27.740000,1.000000,0.871000,8.78000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,34.370000,50.000000

In [15]:
kurtosis(data)

array([37.76576533,  4.53114395, -1.23080466,  9.50303951, -0.09739514,
        2.25815764, -0.89315688,  0.6363019 , -1.02283489, -1.22854637,
       -0.23880684,  6.64675485,  0.07501379,  1.69229742])

# A positive value tells you that you have heavy-tails (i.e. a lot of data in your tails).
# A negative value means that you have light-tails (i.e. little data in your tails).
# Mesokurtic distributions are technically defined as having a kurtosis of zero, although the distribution doesnâ€™t have to be exactly zero in order for it to be classified as mesokurtic. The most common mesokurtic distributions are:

The normal distribution.
Any distribution with a Gaussian (normal) shape and zero probability at other places on the real line.
The binomial distribution is mesokurtic for some values (i.e. for p = 1/2Â±âˆš(1/12).

In [16]:
kurtosis(data)-3

array([34.76576533,  1.53114395, -4.23080466,  6.50303951, -3.09739514,
       -0.74184236, -3.89315688, -2.3636981 , -4.02283489, -4.22854637,
       -3.23880684,  3.64675485, -2.92498621, -1.30770258])

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'black', 'lstat', 'medv'],
      dtype='object')

# Outerlier Analysis Steps

# Outerlier Dection

## step1 :- Find the mean, standard deviation
## Step2 :- Find the cutoff value
                    # 1 Standard Deviation from the Mean: 68%
                    # 2 Standard Deviations from the Mean: 95%
                    # 3 Standard Deviations from the Mean: 99.7%
# Find the lower limit and upper limit using the ""+ or - "" to the cutoff values

In [96]:
data

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.15876,0.0,10.81,0.0,0.413,5.961,17.5,5.2873,4.0,305.0,19.2,376.94,9.88,21.7
1,0.10328,25.0,5.13,0.0,0.453,5.927,47.2,6.9320,8.0,284.0,19.7,396.90,9.22,19.6
2,0.34940,0.0,9.90,0.0,0.544,5.972,76.7,3.1025,4.0,304.0,18.4,396.24,9.97,20.3
3,2.73397,0.0,19.58,0.0,0.871,5.597,94.9,1.5257,5.0,403.0,14.7,351.85,21.45,15.4
4,0.04337,21.0,5.64,0.0,0.439,6.115,63.0,6.8147,4.0,243.0,16.8,393.97,9.43,20.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399,9.32909,0.0,18.10,0.0,0.713,6.185,98.7,2.2616,24.0,666.0,20.2,396.90,18.13,14.1
400,51.13580,0.0,18.10,0.0,0.597,5.757,100.0,1.4130,24.0,666.0,20.2,2.60,10.11,15.0
401,0.01501,90.0,1.21,1.0,0.401,7.923,24.8,5.8850,1.0,198.0,13.6,395.52,3.16,50.0
402,0.02055,85.0,0.74,0.0,0.410,6.383,35.7,9.1876,2.0,313.0,17.3,396.90,5.77,24.7
403,0.08244,30.0,4.93,0.0,0.428,6.481,18.5,6.1899,6.0,300.0,16.6,379.41,6.36,23.7

In [104]:
def OutlierAnalysis(data,col):
    data=data[col]
    data_mean,data_std=mean(data),std(data)
    cut_off=data_std*3
    lower,upper=data_mean-cut_off,data_mean+cut_off
    outliers = [x for x in data if x < lower or x > upper]
    outliers_removed = [x for x in data if x >= lower and x <= upper]
    return outliers,outliers_removed

In [106]:
# data=data
col='crim'
data=data
Outliers,No_Outlier=OutlierAnalysis(data,col)

In [107]:
len(No_Outlier)

397

In [9]:
def Outlier_Analysis(data,col):
    data=data[col]
    Q25,Q75=percentile(data,25),percentile(data,75)
    IQR=Q75-Q25
    Cutoff=IQR*1.5
    lower,upper=Q25-Cutoff,Q75+Cutoff
    outliers = [x for x in data if x < lower or x > upper]
    outliers_removed = [x for x in data if x >= lower and x <= upper]
    return outliers_removed

In [10]:
col='crim'
data=data
Outlier_Analysis(data,col)

[0.15876,
 0.10328,
 0.3494,
 2.73397,
 0.04337,
 0.0837,
 0.19073,
 0.26938,
 1.41385,
 0.09252,
 1.00245,
 0.11027,
 5.70818,
 0.1029,
 1.6566,
 1.42502,
 9.33889,
 0.59005,
 0.08707,
 0.06664,
 0.02498,
 0.25356,
 5.66637,
 0.02187,
 0.04819,
 0.07244,
 0.01439,
 0.06888,
 0.08199,
 0.31827,
 0.18159,
 0.05602,
 0.44791,
 4.66883,
 0.21038,
 3.83684,
 2.37934,
 0.04462,
 5.82115,
 4.26131,
 0.21977,
 4.34879,
 3.53501,
 0.53412,
 9.18702,
 0.82526,
 0.02177,
 0.31533,
 5.73116,
 0.22188,
 0.0315,
 0.33045,
 0.63796,
 8.24809,
 0.04932,
 0.04203,
 0.02729,
 0.03537,
 0.21719,
 0.35233,
 0.10959,
 0.03445,
 5.66998,
 0.10793,
 0.12802,
 0.07503,
 4.54192,
 0.03932,
 7.67202,
 0.03871,
 4.22239,
 0.7258,
 9.72418,
 4.83567,
 4.81213,
 3.1636,
 0.5405,
 0.02731,
 0.10153,
 0.57834,
 0.03306,
 8.20058,
 1.13081,
 0.14231,
 8.71675,
 0.19539,
 0.77299,
 0.03705,
 0.37578,
 9.92485,
 0.12744,
 0.01778,
 0.06588,
 0.08221,
 0.6147,
 0.2909,
 0.01501,
 0.01301,
 1.22358,
 0.02985,
 0.05497,
 0.01709,
 0.03768,
 4.0974,
 0.1396,
 0.3692,
 0.1676,
 6.96215,
 2.63548,
 0.17331,
 0.84054,
 0.02763,
 2.77974,
 0.75026,
 0.28955,
 0.07022,
 0.05479,
 0.06417,
 0.11504,
 0.08308,
 2.3004,
 0.06905,
 5.09017,
 0.0578,
 0.40771,
 0.04297,
 1.35472,
 7.99248,
 0.11747,
 0.18337,
 0.17505,
 6.44405,
 0.09103,
 3.47428,
 0.13587,
 1.19294,
 5.82401,
 0.19657,
 0.0536,
 1.61282,
 0.38214,
 0.12579,
 3.32105,
 9.59571,
 0.02009,
 0.0795,
 0.09744,
 0.85204,
 0.08014,
 3.8497,
 0.62356,
 3.69695,
 0.17004,
 2.24236,
 0.80271,
 0.06263,
 0.07013,
 0.02899,
 0.29916,
 5.44114,
 0.22212,
 0.09378,
 0.18836,
 0.02875,
 0.11432,
 0.26363,
 0.08447,
 8.15174,
 0.24103,
 0.04666,
 0.09849,
 0.65665,
 2.14918,
 0.6718,
 0.12932,
 1.27346,
 0.08387,
 0.61154,
 0.10612,
 0.06127,
 7.40389,
 0.13914,
 0.35809,
 6.39312,
 5.69175,
 0.55007,
 0.04981,
 0.04011,
 0.19186,
 8.79212,
 0.09299,
 0.06076,
 7.52601,
 1.12658,
 0.13642,
 1.49632,
 0.20746,
 4.03841,
 7.05042,
 0.04417,
 1.46336,
 0.09178,
 0.07875,
 0.11329,
 0.06211,
 0.15038,
 0.0187,
 0.28392,
 4.55587,
 6.80117,
 0.22489,
 9.96654,
 0.10469,
 0.12816,
 0.23912,
 6.71772,
 0.26169,
 2.44953,
 0.2896,
 0.07978,
 0.03738,
 0.03659,
 0.34109,
 0.0456,
 0.04301,
 0.10659,
 0.05425,
 8.98296,
 0.14103,
 0.1403,
 0.14476,
 0.03551,
 0.05646,
 0.1265,
 0.52058,
 0.17142,
 0.08829,
 0.13554,
 2.81838,
 1.34284,
 7.75223,
 0.03113,
 1.51902,
 8.64476,
 5.29305,
 0.07165,
 0.49298,
 7.02259,
 0.24522,
 0.29819,
 2.3139,
 0.12269,
 0.14052,
 0.0686,
 7.83932,
 0.95577,
 2.44668,
 0.20608,
 0.05059,
 1.20742,
 0.03041,
 0.2498,
 0.62739,
 0.17446,
 0.09512,
 0.13158,
 0.05735,
 0.25199,
 0.0459,
 0.57529,
 0.19133,
 0.07896,
 0.09266,
 0.1415,
 0.32264,
 8.49213,
 0.03237,
 4.75237,
 0.01381,
 0.1712,
 0.44178,
 0.46296,
 0.36894,
 0.1146,
 0.03584,
 0.7857,
 0.98843,
 0.05561,
 5.87205,
 0.04527,
 0.35114,
 0.79041,
 0.13262,
 0.21409,
 0.11132,
 0.17899,
 9.51363,
 0.14455,
 0.12757,
 9.91655,
 0.03502,
 3.56868,
 0.40202,
 0.05372,
 0.11425,
 0.10574,
 0.06047,
 6.65492,
 0.04113,
 0.1,
 9.2323,
 0.14866,
 0.66351,
 0.10008,
 0.54452,
 2.01019,
 0.05789,
 1.15172,
 0.13058,
 0.03049,
 0.16439,
 0.01951,
 0.06642,
 0.05083,
 0.04544,
 0.21124,
 0.06151,
 4.42228,
 0.38735,
 0.00632,
 0.04684,
 0.09065,
 0.05302,
 2.33099,
 0.14932,
 4.64689,
 7.36711,
 0.06617,
 0.15936,
 3.67822,
 0.06911,
 6.53876,
 5.58107,
 0.25387,
 3.67367,
 9.82349,
 0.0136,
 0.33147,
 0.22969,
 1.05393,
 0.02543,
 0.08826,
 0.03359,
 0.08265,
 0.05188,
 0.06899,
 0.10084,
 0.67191,
 9.32909,
 0.01501,
 0.02055,
 0.08244]